### PR TITLE
CreateTransferAgreementView: Alerts on Identical Agreements

### PR DESCRIPTION
**Pull request by vahidbazzaz**
This PR add alert on identical agreement and implement test case 4.1.5.

### CODE REVIEW

**Comment by vahidbazzaz** [comment]
[2.0 Prevent creating identical agreements](https://trello.com/c/dDBHAzk3/1246-20-prevent-creating-identical-agreements)

**Review by HaGuesto — APPROVED** [review]

**Comment by pylipp** [comment]
@vahidbazzaz @HaGuesto I tested this and it does not work as expected. On v2-staging, I log in as boxaid dev-coordinator, and create a new agreement with BoxCare (all bases, bidirectional). On submitting the form two error messages appear: "something went wrong" and "Your changes could not be saved". But not "Can’t create agreement, an active identical agreement exists"

**Comment by HaGuesto** [comment]
@pylipp weird. It is working for me locally and the test is fine, but it also does not work on staging. I take a look.

**Comment by HaGuesto** [comment]
There is no consistent behavior atm. I managed to make it work with the correct error message, but I also was able to reproduce the state in staging without knowing exactly how. @vahidbazzaz

**Pull request merged**
