### PR TITLE
Renaming in back-end codebase

### PR DESCRIPTION
**Pull request by pylipp**
Mostly renaming :) no functional changes. CI and local Docker services confirmed to work.

### CODE REVIEW

**Comment by pylipp** [comment]
[Renaming in BE codebase](https://trello.com/c/lO58pC84/793-renaming-in-be-codebase)

**Comment by pylipp** [comment]
@vahidbazzaz If you have no objections, I'd merge this before the hackathon to avoid conflicts if people work on BE code :slightly_smiling_face:

**Comment by vahidbazzaz** [comment]
@pylipp I have no objections as I'm sure you have already verified all the configuration and the path.

**Review by vahidbazzaz — APPROVED** [review]

**Comment by pylipp** [comment]
FYI @HaGuesto @spaudanjo @leo-labs the back-end directory is now called `back/`, and the Python package `boxtribute-server`. On latest master you might have to run this in your venv:

```
pip uninstall boxwise-flask
pip install -U -e back
```

Also the docker-compose services `flask` and `mysql` are renamed to `webapp` and `db`.

**Pull request merged**
