### PR TITLE
Improve complex GraphQL queries

### PR DESCRIPTION
**Pull request by pylipp**
I had another look at the performance of the BoxesForBase query.
Using a profiler I found three bottlenecks:

- Avoid unnecessary SELECT for product gender ID (this is a peewee caveat, fixed)
- Remove redundant query for box place (was fixed in #292 but re-introduced when renaming happened, fixed)
- resolving `boxes { elements { product { } } }` results in a lot of separated SELECT queries for products (same for size, presumably). I hacked a basic loader (storing a single call of `Product.select()` in a dictionary) which brought down runtime of the product resolver from 1.4s to 0.14s

As a conclusion from the third bottleneck, and because the other slow queries have similar complexity, I think we defs have to look into data loaders.

FYI @aerinsol

### CODE REVIEW

**Comment by pylipp** [comment]
[Improve performance of boxes-for-base query in boxtribute 2.0](https://trello.com/c/1kJ9lewB/919-improve-performance-of-boxes-for-base-query-in-boxtribute-20)

**Comment by aerinsol** [comment]
@pylipp feel free to look into an example dataloader when the sponsorship comes online. What I've seen seems to show it conflicting with Flask and our current middleware, and solvable by writing resolvers as fragments. But we can do a deep dive on this together with @spaudanjo and later @vahidbazzaz

**Review by spaudanjo — DISMISSED** [review]

**Comment by spaudanjo** [comment]
Amazing @pylipp - performance improved a lot! :D

**Review by spaudanjo — APPROVED** [review]

**Review by vahidbazzaz — COMMENTED** [review]
@pylipp nice job!

**Pull request merged**
