### PR TITLE
Update shipment GraphQL API part 3

### PR DESCRIPTION
**Pull request by pylipp**
This PR changes two things:
1. `Shipment.details` returns **all** (non-deleted and deleted) details of the shipment. @HaGuesto @vahidbazzaz not sure if you want to update the FE queries here or in a separate PR.
2. `Box` now has a `shipmentDetail` field, so one can query shipment information for a box through `box(labelIdentifier: XY) { shipmentDetail { shipment { id } } }`

### CODE REVIEW

**Comment by HaGuesto** [comment]
@pylipp I would update the FE in this branch

**Review by HaGuesto — APPROVED** [review]
@pylipp I checked your code and it works

**Comment by HaGuesto** [comment]
@pylipp I added my bit for the shipmentOverview

@vahidbazzaz could you adapt the ShipmentView?

**Review by vahidbazzaz — APPROVED** [review]

**Comment by pylipp** [comment]
I ran a couple of final tests by removing a box from a Preparing shipment:
- the history shows that the box had been added at some point. That's correct
- the counter in the shipments overview is correctly reset
- the counter in the ViewShipment card was not reset. I added a fix for that

**Pull request merged**
