### PR TITLE
Docs: update license formatting and ToS

### PR DESCRIPTION
**Pull request by pylipp**
License is now rendered as markdown: https://github.com/boxwise/boxtribute/blob/docs/833-update-license-and-tos/LICENSE.md

### CODE REVIEW

**Comment by pylipp** [comment]
[Create and update GraphQL API documentation](https://trello.com/c/5oBmg9bp/833-create-and-update-graphql-api-documentation)

**Review by aerinsol — CHANGES_REQUESTED** [review]
For this: 
"In line with the Service Agreement, and other related documents as signed with Boxtribute (Stichting Boxwise)"

Can we put the link www.boxtribute.org *just* on "Boxtribute"? In MD terms: "In line with the Service Agreement and other related documents as signed with _Stichting Boxwise_ a.k.a. [Boxtribute](https://www.boxtribute.org)"

**Comment by pylipp** [comment]
> For this: "In line with the Service Agreement, and other related documents as signed with Boxtribute (Stichting Boxwise)"
> 
> Can we put the link [www.boxtribute.org](http://www.boxtribute.org) _just_ on "Boxtribute"?
> 
> In MD terms:
> 
> > In line with the Service Agreement and other related documents as signed with  [Boxtribute](https://www.boxtribute.org) (_Stichting Boxwise_)
> 
> I don't want to wholly replace the text, nor do I want to just put a link to our webpage.

I'm afraid this is not possible since the config file format builds on the OpenAPI spec which [only allows a string](https://swagger.io/specification/#info-object) for the `termsOfService` field.

**Comment by pylipp** [comment]
2022-03-07-202126_1151x614_scrot

@aerinsol I added a small dedicated section for the ToS (see bottom in screenshot). There is no more link in the panel on the right. Let me know if this works for you :)

**Comment by aerinsol** [comment]
Perfect solution Philipp! Thank you!

**Comment by pylipp** [comment]
Do you mind approving the PR :innocent: ?

**Comment by aerinsol** [comment]
@pylipp sure, but Github wants you to re-request the review :)

**Review by aerinsol — APPROVED** [review]

**Pull request merged**
