### PR TITLE
Fix sidebar bottom cut off due screen size and scaling

### PR DESCRIPTION
**Pull request by fhenrich33**
firefox_VjmiwwXrMd

### CODE REVIEW

**Comment by fhenrich33** [comment]
[2.0 Sidebar's bottom goes below the fold due to screen resolution + scaling #tiny](https://trello.com/c/5RO7N1gA/1641-20-sidebars-bottom-goes-below-the-fold-due-to-screen-resolution-scaling-tiny)

**Comment by fhenrich33** [comment]
@aerinsol WDYT?

**Comment by aerinsol** [comment]
I like it @fhenrich33 , let's do it

**Review by HaGuesto — APPROVED** [review]

**Comment by HaGuesto** [comment]
## code review passed

**Comment by pylipp** [comment]
Great, this fixes the issue I had before :+1:

**Pull request merged**
