### PR TITLE
Show warning toast when trying to export without selected boxes

### PR DESCRIPTION
**Pull request by pylipp**
FYI @HaGuesto @jlin95 @fhenrich33

### CODE REVIEW

**Comment by pylipp** [comment]
[2.0 Export Boxes in Manage Boxes v2 to csv](https://trello.com/c/Z75aPKkc/1566-20-export-boxes-in-manage-boxes-v2-to-csv)

**Comment by pylipp** [comment]
Locally all FE tests pass.

**Comment by jlin95** [comment]
Ah gosh I forgot to add the check for the export functionality, thank you very much @pylipp 🙏🏽

**Comment by pylipp** [comment]
No worries, the PRs happened around the same time and then I didn't think of it either 😅

**Pull request merged**
