### PR TITLE
Replace DB seed with all unsigned ids

### PR DESCRIPTION
**Pull request by HaGuesto**
This is an update of the db seed with all unsigned ids. Please merge directly @pylipp if it works for u.

### CODE REVIEW

**Comment by HaGuesto** [comment]
[check if primary keys are unsigned integers or signed integers #small](https://trello.com/c/KDP3LpVK/693-check-if-primary-keys-are-unsigned-integers-or-signed-integers-small)

**Comment by pylipp** [comment]
Can you rebase this onto current master such that comparison is easier? Also then I can rebase the WIP branch `peewee-unsigned-integer-pks` onto this one.

It appears you also changed a couple of FK properties (on-delete handlers e.g.). I'll have to update the model definitions accordingly. I wouldn't merge before.

**Comment by pylipp** [comment]
List of changed FK properties by tables:
* `borrow_items`
```
CONSTRAINT `borrow_items_ibfk_5` FOREIGN KEY (`created_by`) REFERENCES `cms_users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
CONSTRAINT `borrow_items_ibfk_6` FOREIGN KEY (`modified_by`) REFERENCES `cms_users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
```
* `borrow_transactions`: several changes
* Why is the `id` of the `box_state` table now `unsigned NOT NULL` (no `AUTO_INCREMENT`) ? Same for `cms_functions` table
* `camps`: new fields `beneficiaryisregistered`, and more. Should they be added to the peewee model?. Handlers for `created_by` and `modified_by` fields

**Comment by HaGuesto** [comment]
> Why is the id of the box_state table now unsigned NOT NULL (no AUTO_INCREMENT) ? Same for cms_functions, cms_users, genders, locations, people, products, sizes (@jamescrowley @aerinsol is this related to the failures you've seen on master recently?)

This is my bad. I did something wrong here when writing the migrations.

> camps: new fields beneficiaryisregistered, and more. Should they be added to the peewee model?

only beneficiaryisregistered and beneficiaryisvolunteer

> borrow_*, cms_functions, cms_functions_camps, cms_settings, cms_usergroups, history, itemsout, laundry_*, library_*, people, transactions, translate: changes in the FK fields (but tables not available as peewee models)

don't worry about it. not important for warehousing.

> locations: for box_state_id field, unsigned NOT NULL instead of DEFAULT '1', is that on purpose? same in stock table

my bad. I have to change this.

> new tables people_tags and tags: add as peewee model?

don't worry about it. not important for warehousing.

**Comment by aerinsol** [comment]
@HaGuesto why would you ask @pylipp not to import this into the Peewee model? Yes, it's not important for warehousing, but it is overall important for the back-end.

> > new tables people_tags and tags: add as peewee model?
> 
> don't worry about it. not important for warehousing.

**Comment by HaGuesto** [comment]
@aerinsol We have not implemented peewee models for anything not related to warehousing except user access tables.
I would wait to integrate peewee models for tables until they will be used in the new app. Otherwise we just replicate the "horrible db design" of before and have to edit the models as well when we change the db in the old app.

**Comment by aerinsol** [comment]
I don't actually think this is correct. Due to the pwiz export by @mc18g13 , I believe all of the tables - including _Beneficiary_, _Transactions_, etc. have been exported as peewee models. I don't think **tests** have been created around them, but I think the models are there. @mc18g13 or @pylipp please comment if you know off the top of your head.

**Comment by HaGuesto** [comment]
These are the models that are implemented

image

**Comment by aerinsol** [comment]
OK good to know @HaGuesto. That means this issue log: https://trello.com/c/Ew2XkaDt is incorrect and will be put back again on the backlog. @pylipp for future reference, this is essentially this is just the ability to assign tags to people - I'll tag you in Slack on the video that demos this feature. In the future, we will likely want to align this with the tag boxes feature https://trello.com/c/XjNwO3sL

**Comment by aerinsol** [comment]
[Import Beneficiary/Shop and Log Tables into Peewee models](https://trello.com/c/Ew2XkaDt/695-import-beneficiary-shop-and-log-tables-into-peewee-models)

**Comment by aerinsol** [comment]
@pylipp can you take a look at this?

**Comment by pylipp** [comment]
I'll have a look on Saturday. From what I remember, a correct database dump is needed to base the peewee model definitions upon. I can achieve that by editing the dump I suppose :)

**Review by pylipp — APPROVED** [review]
@HaGuesto ~Can you check the auth0 parameters required for the CircleCI run (or show me how to update them)? It breaks the auth and endpoint tests.~ Fixed by updating the AUTH0_PASSWORD variable in the CircleCI context "staging".

**Comment by pylipp** [comment]
[Create local Peewee support of MySQL default for signed integers](https://trello.com/c/EGkszQwD/697-create-local-peewee-support-of-mysql-default-for-signed-integers)

**Comment by pylipp** [comment]
That's a PR that would be nice to have merged soon =)

**Comment by aerinsol** [comment]
@pylipp done

**Pull request merged**
