### PR TITLE
Set ShipmentDetail.received_by/on immediately after box reconciliation

### PR DESCRIPTION
**Pull request by pylipp**
Can be tested by reconciling a box via the GraphQL playground.

### CODE REVIEW

**Comment by pylipp** [comment]
[2.0 Set ShipmentDetail.received_by/on immediately after box reconciliation](https://trello.com/c/Douee3Mb/1288-20-set-shipmentdetailreceivedby-on-immediately-after-box-reconciliation)

**Review by vahidbazzaz — APPROVED** [review]
Thank you @pylipp, this works as expected, once I reconciled the box, it set the received_on and receive_by on the database. 

@pylipp @aerinsol If you agree, I will push related FE changes to this PR so that in the reconciliation UI box counts are based on received_on rather than boxes' states

**Comment by pylipp** [comment]
@vahidbazzaz is there any advantage of using box states instead of timestamps for counting? Otherwise I find it easier to read code logic that deals with box states.

**Comment by vahidbazzaz** [comment]
> @vahidbazzaz is there any advantage of using box states instead of timestamps for counting? Otherwise I find it easier to read code logic that deals with box states.

@pylipp yes indeed, the count can be incorrect if the box state changes while the other boxes are still reconciling.

**Comment by pylipp** [comment]
@vahidbazzaz sure go ahead!

**Pull request merged**
