### PR TITLE
CreateShipment: Fix to Show Alert When No Active Transfer Agreement Available

### PR DESCRIPTION
**Pull request by vahidbazzaz**
- Alert style change to warning
- Fix caching problem

### CODE REVIEW

**Comment by vahidbazzaz** [comment]
[2.0 BUG: Error message on cannot create shipment if no accepted agreement available](https://trello.com/c/fOtUtarz/1276-20-bug-error-message-on-cannot-create-shipment-if-no-accepted-agreement-available)

**Comment by aerinsol** [comment]
@vahidbazzaz @HaGuesto caching issue isn't fixed.

**Comment by vahidbazzaz** [comment]
> @vahidbazzaz @HaGuesto caching issue isn't fixed.

@aerinsol  Could you please let me know which user you have tried with, this seems to be working fine with boxaid/boxcare users in staging.

**Comment by aerinsol** [comment]
Well now I can't even renew an agreement with BoxCare without it throwing
an error -_-. Using ***@***.***

I declined everything, created two new agreements with
TestOrg/DummyTestOrgwithBoxes, and then when I tried to renew with Boxcare
I just get errors.

**Pull request merged**
