### PR TITLE
BoxView: Adds All Shipment Actions

### PR DESCRIPTION
**Pull request by vahidbazzaz**
PR includes the first iteration of BoxView with transfer capabilities, as well as major refactoring the component structure.

Implemented functionalities:
-  Assigning boxes to shipments
- Removing the box from the shipment
- Reassignment of the box to a different shipment

Missing: 
Tests

### CODE REVIEW

**Comment by vahidbazzaz** [comment]
[2.0 BoxView for all Shipment actions](https://trello.com/c/fllli6mZ)

**Review by pylipp — COMMENTED** [review]
Implemented functionality works as expected, thanks :smile: 

Please do not merge to master since it contains the QrReaderMultiScan changes.

@vahidbazzaz one thing I noticed: as dev_coordinator@boxaid.org I tried to assign box 8889639 to a shipment which fails because the box is Donated (not InStock). Should the transfer tab be disabled then?

**Review by pylipp — APPROVED** [review]
@vahidbazzaz @HaGuesto this needs master merged but otherwise good from my side

**Comment by HaGuesto** [comment]
[2.0 BoxView for all Shipment actions - write test case + tests + ui](https://trello.com/c/fllli6mZ/1180-20-boxview-for-all-shipment-actions-write-test-case-tests-ui)

**Comment by pylipp** [comment]
@HaGuesto I wonder why you merged this PR although tests were failing? This means that later PR merges like the #806 are not deployed to staging.

**Comment by HaGuesto** [comment]
@pylipp my logic was:
There are tests missing here. I'm touching tests again to also control other parts of the PRs that were merged, but that I did not review.
To not be a further bottleneck (so that Roanna can test) and to bring the code together (making it easier for me to get an overview), I merged the PRs that I was ok with from the code review side.

I see now that my plan was flawed since it does not deploy if tests are failing....
I'm sorry. I also should have made a note about this and not just merge last minute before I leave for the weekend.

**Pull request merged**
