### PR TITLE
Use batch-loading in box-transfer fields

### PR DESCRIPTION
**Pull request by pylipp**
Comparison of SELECT calls before:
~3 - 5s

     48 FROM `camps`
     89 FROM `cms_users`
      1 FROM `distro_events`
     77 FROM `history`
      2 FROM `locations`
     43 FROM `organisations`
      1 FROM `product_categories`
     83 FROM `products`
    106 FROM `shipment`
     84 FROM `shipment_detail`
      1 FROM `sizegroup`
      2 FROM `sizes`
     77 FROM `stock`
      1 FROM `tags_relations`
      7 FROM `transfer_agreement`

After:
1.5s

      1 FROM `camps`
      1 FROM `cms_users`
      1 FROM `distro_events`
     77 FROM `history`
      3 FROM `locations`
      2 FROM `organisations`
      1 FROM `product_categories`
      2 FROM `products`
      9 FROM `shipment`
      9 FROM `shipment_detail`
      1 FROM `sizegroup`
      3 FROM `sizes`
      2 FROM `stock`
      2 FROM `tags_relations`
      7 FROM `transfer_agreement`

### CODE REVIEW

**Comment by pylipp** [comment]
[2.0 Check and enhance performance of transfer-related queries](https://trello.com/c/Lav5ploi/1129-20-check-and-enhance-performance-of-transfer-related-queries)

**Comment by HaGuesto** [comment]
@pylipp I feel like we should have a call about this. I have no clue how batch loading works and there should be a second person to understand.

Also would be nice then to let me know what I should test here.

**Comment by pylipp** [comment]
good point @HaGuesto let's talk next week. In the meantime you can check [this readme](https://github.com/syrusakbary/aiodataloader) if you want

**Review by HaGuesto — APPROVED** [review]
## code review
passed in code review

## functional review
I wasn't really sure how to check this. Let's see if the performance improves for Roanna

**Pull request merged**
