### PR TITLE
Revert previous solutions, add to iOS warning text

### PR DESCRIPTION
**Pull request by fhenrich33**

### CODE REVIEW

**Comment by fhenrich33** [comment]
[2.0 FE Bug: Multibox scan tab on iPhone forwards to single box details (behavior of single box scan)](https://trello.com/c/xW6kNcsv/1598-20-fe-bug-multibox-scan-tab-on-iphone-forwards-to-single-box-details-behavior-of-single-box-scan)

**Comment by fhenrich33** [comment]
[BUG: No iPhone camera access in QR scanner even after giving permissions](https://trello.com/c/HjvYpFRC/1528-bug-no-iphone-camera-access-in-qr-scanner-even-after-giving-permissions)

**Comment by fhenrich33** [comment]
@HaGuesto @aerinsol @pylipp I'll merge to test in an iPhone on staging, otherwise this is nightly impossible to debug on iOS specifically. Will revert if needed.

**Review by HaGuesto — COMMENTED** [review]
## code review passed

**Pull request merged**
