### PR TITLE
Add tracking by image download type

### PR DESCRIPTION
**Pull request by jlin95**
Extended heap tracking event with the image download type. 

Would have liked to add tests in this iteration but couldn't run tests for FE, see thread: https://boxwise.slack.com/archives/CB1UYDGLU/p1724450618067419?thread_ts=1724361187.607409&cid=CB1UYDGLU - will definitely add tests when I can address this.

### CODE REVIEW

**Comment by jlin95** [comment]
@HaGuesto not an urgent PR :)

**Review by HaGuesto — APPROVED** [review]
@jlin95 Thank you! Pls do not forget to add this also in your console print to check if the right values are passed.

**Comment by jlin95** [comment]
Hey @HaGuesto, I did that when I did local testing. Do you need me to modify the getHeap function further to include extra logging?

**Comment by jlin95** [comment]
I can't merge this PR, so you'd need to merge it or someone else @HaGuesto :) (It says `The base branch restricts merging to authorized users`.)

**Pull request merged**
