### PR TITLE
Incorporate QR Scan Into Mobile Menu

### PR DESCRIPTION
**Pull request by vahidbazzaz**
The PR incorporates QR scanning into the mobile menu

### CODE REVIEW

**Comment by vahidbazzaz** [comment]
[2.0 HeaderMenuMobile: Incorporate QR scan into mobile menu](https://trello.com/c/Bl8DzjmL)

**Review by pylipp — APPROVED** [review]
### Functional review
- in wide desktop view, there is no QR button in the header and no QR button in the menu
- in narrow desktop view and in mobile view, there is no QR button in the header but a QR button in the menu
- the menu does not auto-close when I've clicked the QR button. Personally I find it inconvenient having to manually close it via the X-button.

**Comment by aerinsol** [comment]
I then want to prioritize this as one of the things that should go into the next release as well. @pylipp

**Comment by vahidbazzaz** [comment]
> @vahidbazzaz Can you fix the menu auto-close issue?

@aerinsol @pylipp I just changed the menu to close when the QR menu item is clicked

**Pull request merged**
