### PR TITLE
Inspect boxes-query performance

### PR DESCRIPTION
**Pull request by pylipp**
I inspected SQL generated by peewee, and profiled the stack of the app when executing the `boxes` GraphQL query while using a production DB dump.

### Findings

- I could improve filtering of the select-query (filter on join instead of where)
- I added a filter for non-deleted boxes
- when a large result is queried, there will be overhead with both peewee and ariadne
    - peewee as the ORM will have significant overhead transforming the raw SQL rows into Python objects (e.g. datetime parsing is quite costly)
    - ariadne will issue an enormous amount of function calls to resolve the query fields (e.g. for each box the location and product), and since these make use of batch-loading, the eventual resolving of awaitables has an overhead, too

### Possible solutions braindump

- smaller size of requested data (i.e. true pagination, only instock boxes, see #1157)
- hand-craft a single SQL query in the `boxes` resolver (this somewhat defeats the purpose of GraphQL)
- experiment with a new, synchronous [batch-loading library](https://github.com/jkimbo/graphql-sync-dataloaders): in order to use the `aiodataloader` library, currently an asyncio routine is patched into the (sync) Flask app with the (sync) ORM peewee. Maybe this generates significant overhead.
- in combination with the previous, try to speed up Python execution time using [gevent](https://docs.peewee-orm.com/en/latest/peewee/database.html#async-with-gevent) async execution

### CODE REVIEW

**Comment by pylipp** [comment]
[2.0 BE Performance: excessive loading times of BE request for BoxesView](https://trello.com/c/SsA0hd3O/1337-20-be-performance-excessive-loading-times-of-be-request-for-boxesview)

**Comment by HaGuesto** [comment]
@pylipp code review is passing. I will merge this now, nur check again if delete Boxes are not part of the result.

**Comment by HaGuesto** [comment]
Functional review is also passing. @pylipp  I was a bit confused since you filtered for deleted Boxes in the ON clause of the join function.

Is this join function than an inner join and not a left join?

**Comment by pylipp** [comment]
> Functional review is also passing. @pylipp I was a bit confused since you filtered for deleted Boxes in the ON clause of the join function.
> 
> Is this join function than an inner join and not a left join?

It's an inner join.

**Pull request merged**
