### PR TITLE
Fix Loads Issue in ShipmentView, BoxView, and ShipmentOverview by Restricting ShipmentDetail Fragments

### PR DESCRIPTION
**Pull request by vahidbazzaz**
- remove extra fields from ShipmentDetailFields fragment
- remove support for graphql partial response
- apply change in ShipmentView to use sourceSize, sourceProduct, sourceQuantity instead of box

### CODE REVIEW

**Comment by vahidbazzaz** [comment]
[2.0 BUG: There are some BoxView tests that fail due to cache, and BoxView fails to load due to partial GraphQL response](https://trello.com/c/7YyWlrlo/1233-20-bug-there-are-some-boxview-tests-that-fail-due-to-cache-and-boxview-fails-to-load-due-to-partial-graphql-response)

**Review by pylipp — APPROVED** [review]
LGTM, thanks for refactoring in order to use the `source*` fields :) 
@vahidbazzaz once the failing test is fixed this can be merged.

**Comment by pylipp** [comment]
@vahidbazzaz would using `box.shipmentDetail.shipment` help anything here?

**Comment by vahidbazzaz** [comment]
[2.0 Fix Loads Issue in ShipmentView, BoxView, and ShipmentOverview by Restricting ShipmentDetail Fragments](https://trello.com/c/bXDowXpI/1235-20-fix-loads-issue-in-shipmentview-boxview-and-shipmentoverview-by-restricting-shipmentdetail-fragments)

**Pull request merged**
