### PR TITLE
Remove failing flaky tests from forEach loop

### PR DESCRIPTION
**Pull request by fhenrich33**
I removed the tests out of the `forEach` so the functions can be hoisted. Hopefully, those specs won't time out again.

Got to handle the other flaky tests at some point, though.

### CODE REVIEW

**Comment by fhenrich33** [comment]
[2.0 Flaky 4.8.1.2 test](https://trello.com/c/5UfwfW6U/1435-20-flaky-4812-test)

**Comment by fhenrich33** [comment]
Trying to fix a flaky test, another one pops up to make me feel silly:

image

**Comment by fhenrich33** [comment]
[2.0 flaky FE test 4.8.2.1](https://trello.com/c/RnWDDglX/1463-20-flaky-fe-test-4821)

**Comment by fhenrich33** [comment]
[2.0 flaky FE test 4.8.2.1](https://trello.com/c/RnWDDglX/1463-20-flaky-fe-test-4821)

**Review by HaGuesto — APPROVED** [review]

**Pull request merged**
