### PR TITLE
Receiving and Sorting tabs for Manage Shipments, default sort to last updated

### PR DESCRIPTION
**Pull request by fhenrich33**
firefox_wEgMAYMgi1

### CODE REVIEW

**Comment by pylipp** [comment]
One quick remark, telling from the GIF: the shipments currently listed in Receiving should be in Sending and vice versa (you can tell from the shipment identifier; the last part is `<first two letters of sending base>x<first two letters of receiving base>`, so since the user is in Thessaloniki, when in the Receiving tab, the `TH` should be second in the identifier). I didn't find the sorting logic in the code but basically the Receiving tab should contain all shipments with `shipment.targetBase === currentBase`

**Comment by fhenrich33** [comment]
> One quick remark, telling from the GIF: the shipments currently listed in Receiving should be in Sending and vice versa (you can tell from the shipment identifier; the last part is `<first two letters of sending base>x<first two letters of receiving base>`, so since the user is in Thessaloniki, when in the Receiving tab, the `TH` should be second in the identifier). I didn't find the sorting logic in the code but basically the Receiving tab should contain all shipments with `shipment.targetBase === currentBase`

Thanks @pylipp. That also was an opportunity to revisit the overall direction calculation for the shipments now that we support intra-org shipments. I think this should do the trick.

**Review by HaGuesto — APPROVED** [review]
well done. 

# code review and functional review passed

**Comment by aerinsol** [comment]
@fhenrich33 @HaGuesto  the count of shipments at the top tab should exclude canceled and completed shipments.

**Comment by pylipp** [comment]
> @fhenrich33 @HaGuesto the count of shipments at the top tab should exclude canceled and completed shipments.

addressed in #1834

**Pull request merged**
