### PR TITLE
Fix frontend deploy

### PR DESCRIPTION
**Pull request by pylipp**
Please test that login and logout work at https://v2-staging.boxtribute.org

@spaudanjo I'm not sure where/if the env variables `REACT_APP_REDIRECT` and `REACT_APP_LOGOUT_URL` are used in the FE code at all?

### CODE REVIEW

**Comment by pylipp** [comment]
@spaudanjo I had this PR already finalized and opened for review, the last force-push overwrote this changes unfortunately. I'll push again from my side and hope for a review :sweat_smile:

**Comment by spaudanjo** [comment]
@pylipp What would in the end the domain schema then be after this PR is merged? 
In any way, I approve already.

**Review by spaudanjo — APPROVED** [review]

**Comment by spaudanjo** [comment]
Regarding REACT_APP_REDIRECT and REACT_APP_LOGOUT_URL: apparently they are not used atm. They might be in the future needed again though (not sure about the auth0 flow details here atm), but then let's delete them for now?

**Comment by pylipp** [comment]
> @pylipp What would in the end the domain schema then be after this PR is merged? In any way, I approve already.

As indicated in the Readme: https://github.com/boxwise/boxtribute/pull/173/files#diff-9fc094e56df752d8dcf487966176bc69b34358f42c9b92153883557c91dddb06R266 :smile: I'll update the 'How to cut a release' document, too.

**Pull request merged**
