### PR TITLE
Fix desktop menu position and layout

### PR DESCRIPTION
**Pull request by fhenrich33**
firefox_8ID1BKaAcK

### CODE REVIEW

**Comment by fhenrich33** [comment]
[2.0 BUG align where toasts are shown on desktop #tiny](https://trello.com/c/dCOHzF9O/1609-20-bug-align-where-toasts-are-shown-on-desktop-tiny)

**Comment by fhenrich33** [comment]
[2.0 Bug: Desktop Menu on the right enforces large margin on the right besides it](https://trello.com/c/U18IlaiE/1607-20-bug-desktop-menu-on-the-right-enforces-large-margin-on-the-right-besides-it)

**Comment by aerinsol** [comment]
>  [2.0 BUG align where toasts are shown on desktop #tiny](https://trello.com/c/dCOHzF9O/1609-20-bug-align-where-toasts-are-shown-on-desktop-tiny)

Toasts should be upper right hand corner on desktop as discussed

**Comment by aerinsol** [comment]
Bottom right hand corner is also ok

**Comment by fhenrich33** [comment]
> >  [2.0 BUG align where toasts are shown on desktop #tiny](https://trello.com/c/dCOHzF9O/1609-20-bug-align-where-toasts-are-shown-on-desktop-tiny)
> 
> Toasts should be upper right hand corner on desktop as discussed

@aerinsol Apologies, it totally slipped my mind. Fixed, and GIFs updated!

**Review by HaGuesto — APPROVED** [review]
## code and functional review passed

great work @fhenrich33

**Pull request merged**
