### PR TITLE
Auth0 Apollo Migration

### PR DESCRIPTION
**Pull request by HaGuesto**
@lguilhermef @billyhao12 
I would like to have a review from both of you. the aim is that you understand what we wrote there before moving on. Also feel free to check it out and test it.
I even added another Wrapper for Auth0 to connect to the Router history following [this guide](https://auth0.com/blog/complete-guide-to-react-user-authentication/#Set-Up-the-Auth0-React-SDK). This way the user isalways redirected to the url they requested after the authentication.

## References
https://github.com/samjulien/apollo-auth0-fullstack/blob/master/habit-tracker/src/ApolloWrapper.js
https://www.youtube.com/watch?v=FROhOGcnQxs
https://auth0.com/blog/complete-guide-to-react-user-authentication/#Set-Up-the-Auth0-React-SDK

@mcgnly This is the migration I was mentioning in our last call. Feel free to check it out and leave a review. Not mandatory though :). I will wait a few days and merge it otherwise.

### CODE REVIEW

**Comment by HaGuesto** [comment]
[Migrate Auth0 to React SPA SDK instead of auth0.js #react #large](https://trello.com/c/eJ9TBiwS/636-migrate-auth0-to-react-spa-sdk-instead-of-auth0js-react-large)

**Comment by HaGuesto** [comment]
forgot to push the package.json

**Comment by mcgnly** [comment]
I’ll take a look, but on Friday, as we discussed

**Review by billyhao12 — APPROVED** [review]
I admit that this is all still quite complex to me. I only understand that the ApolloWrapper is being used to compensate for the changed format for establishing a new ApolloClient.

**Review by mcgnly — APPROVED** [review]
looks reasonable to me! I like that you provided links to where you found the references 🎉

**Pull request merged**
