### PR TITLE
Replace icons and update button variant in BoxCard

### PR DESCRIPTION
**Pull request by jlin95**
**Trello Card:**
https://trello.com/c/9yy6lF3t/1457-tiny-20-boxview-use-chakra-ui-for-button-icons

**Changelog:**
Replace <AddIcon /> and <MinusIcon /> usage with alternatives from `react-icon` library. Also updated the BoxView button variants to `ghost`. 

**Before:**
Screenshot 2024-07-20 at 19 14 32

**After:**
Screenshot 2024-08-04 at 12 13 53

### CODE REVIEW

**Review by fhenrich33 — APPROVED** [review]
Looks good! (Although I would prefer the icons to be slightly larger, WDYT @aerinsol ?) 

I'd remove the `package-lock.json` since our repo doesn't use npm, tho.

**Comment by aerinsol** [comment]
Sorry to be that person but I'd really like to change those icons, I'm not a fan. Give me some time to propose an alternate layout possibly over the weekend.

**Comment by jlin95** [comment]
No worries, just let me know which ones you'd like me to replace them with. 

For the icon size, I think I set them to the largest size 'lg' already. Perhaps a different set of icons would look better.

**Comment by aerinsol** [comment]
[#tiny 2.0 BoxView - Use selected   button icons and make the button ghost style](https://trello.com/c/9yy6lF3t/1457-tiny-20-boxview-use-selected-button-icons-and-make-the-button-ghost-style)

**Comment by aerinsol** [comment]
FYI @jlin95 - if you use the Github Trello Power Up Attachment when attaching your PR, it will automatically cross-link the two and save you some time :)

**Comment by jlin95** [comment]
Need help with rerunning failing flaky test here https://app.circleci.com/pipelines/github/boxwise/boxtribute/5142/workflows/5bbfb8a3-8107-4de6-a004-b1cffde3b677/jobs/28077/tests. 

I have signed in to CircleCi, but can't rerun (see screenshot), it just brings me to a new page with instructions on setting up.
image

Maybe @HaGuesto knows something or @fhenrich33 ?

**Comment by jamescrowley** [comment]
@jlin95 I’ll re-run but it’s basically hit and miss. I'm looking at ways to solve this I would get @fhenrich33 @aerinsol  to approve the PR, and then we can merge ignoring this test failure.

**Comment by jlin95** [comment]
@jamescrowley Noted that! @fhenrich33 has already appproved the PR but I'm still blocked from merging, since @aerinsol is out for a bit. 
I'm also seeing this: 
Screenshot 2024-08-04 at 11 18 04
so maybe someone else needs to do so?

**Comment by aerinsol** [comment]
Sorry, I'm still not super happy with the outcome compared to the shipments view. Unless it's possible to make the two look more similar I'd like to hold off on this, and move ahead to the next feature. @vahidbazzaz has worked with me on UI before, maybe you can share some tips with @jlin95?

**Comment by jlin95** [comment]
No worries @aerinsol, I found out how to make it similar to ShipmentCard. Have a look again and if it still doesn't fit the requirements, I'd move on :)

**Comment by jlin95** [comment]
test-front is flaky, running frontend tests locally works and everything passed.

**Comment by aerinsol** [comment]
Good solution @jlin95 , but I think the spacing will be hard for fat fingerer people to hit. I already have a half done design - I thought this would be an easy improvement but it's not working out. If you could prioritize the other tasks instead that would be great - since those are tied to our goals.

**Comment by jlin95** [comment]
I'd close this PR for now until a firmer design is in place. Happy to see the design if you have it in Figma/etc.

**Pull request closed without merging**
