### PR TITLE
Create GraphQL documentation

### PR DESCRIPTION
**Pull request by pylipp**
Here comes the documentation of our GraphQL documentation.

After some research, I decided to use [SpectaQL](https://github.com/anvilco/spectaql) for generation (I consider it an active, well-documented project. Indeed it was very easy to set up). The generated GraphQL documentation (excluding mutations) is attached to the linked Trello card. Please extract it and have a look at `index.html` in your web browser. I really like the interactivity of the documentation framework.

As a preparation I split the schema definitions into several files:
- "external" API consumers access queries and relevant types (no mutations)
- our front-end consumes the full schema (queries, types, mutations, inputs)

I have a local repository for building the documentation. What do you think about putting the relevant instructions and scripts into `docs/graphql-api/` @aerinsol @vahidbazzaz? For now it can be build and distributed from there. Later we might want to think about hosting the documentation online (and introspecting the production server for information about the GraphQL schema).

### CODE REVIEW

**Comment by pylipp** [comment]
[Create and update GraphQL API documentation](https://trello.com/c/5oBmg9bp/833-create-and-update-graphql-api-documentation)

**Comment by pylipp** [comment]
[Create and update GraphQL API documentation](https://trello.com/c/5oBmg9bp/833-create-and-update-graphql-api-documentation)

**Comment by vahidbazzaz** [comment]
@pylipp Looks very clean and nice, a good choice! I think it makes complete sense to have it in repository and perhaps expose to end users later.

**Review by vahidbazzaz — APPROVED** [review]

**Review by aerinsol — APPROVED** [review]
Great choice with SpectaQL, looks incredible, fully compatible open-source license. 

@vahidbazzaz may want to look at the open issue here based on his prior experience with OpenAPI / Swagger: https://github.com/anvilco/spectaql/issues/111

**Comment by aerinsol** [comment]
Also agree with @vahidbazzaz suggestion of putting it in the repository.

**Comment by pylipp** [comment]
@spaudanjo @flisowna Might be interesting for you as well! Building documentation of the GraphQL API (viewable in web browser). Feel free to give it a try :smiley:

**Pull request merged**
