### PR TITLE
ShipmentView UI Fixes

### PR DESCRIPTION
**Pull request by vahidbazzaz**
This PR applies minor fixes to the Shipment view [754](https://github.com/boxwise/boxtribute/pull/754) to make the UI align with the mockup design

### CODE REVIEW

**Comment by vahidbazzaz** [comment]
[2.0 ShipmentView UI Fixes](https://trello.com/c/4kl6JLgt)

**Review by pylipp — APPROVED** [review]
## Functional review
The updates make the UI clearer, and there's no text overlap with long base names anymore.
However one important request is to have a popup asking for user confirmation when marking a Sent shipment as lost. Currently this is an immediate action: I click "Cannot locate shipment" at the bottom, or the struck-through-map button in the top right of the shipment card, and the shipment is marked as lost. Since this is a non-reversible action we should have a popup @aerinsol

**Comment by aerinsol** [comment]
Merging to test on master.

**Comment by aerinsol** [comment]
@vahidbazzaz actually, it looks like this merged into a different branch as well. Please remember we are using [Trunk Based development](https://trunkbaseddevelopment.com/), not [Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)/feature branches like this. We should not have multiple long-standing branches. 

Please fix it appropriately.

**Comment by aerinsol** [comment]
@HaGuesto this is the second one. As you can see the other PR (https://github.com/boxwise/boxtribute/pull/764) was two branches away from master. 
@vahidbazzaz please update your first comment on this thread to reference what's needed from the the non-master base

**Pull request merged**
